### PR TITLE
Optimize the Governance dApp for Mobile Viewing

### PR DESCRIPTION
**Pull request by flarcos**
Hi, 
We would like to submit for RFP-1: Optimize the Governance dApp for Mobile Viewing.
Test link for http://3.87.182.171/ (will be on for 7 days from this submission for testing)

### CODE REVIEW

**Comment by dirkpage** [comment]
This looks awesome, here are some things that I noticed that could be improved:

On the `/proposals` route, when I scroll down on mobile and the tab links stick to the top of the viewport, the eco logo partially covers the links, I think the logo should be hidden if the width is so small that there is no room for it. Also the link text gets very close to the top of the viewport, maybe we should add a little padding top there.

And then the `MobileNav` component is using placeholder html for the wallet info and disconnect button, I think that needs to be swapped with a custom style of the `WalletItem` component.

**Comment by flarcos** [comment]
Updated @paged1

**Review by dirkpage — APPROVED** [review]

**Review by dirkpage — COMMENTED** [review]
Thanks for the improvements, looks great. Sorry I just noticed that some of the modals on the account page have a minimum width that is more than a mobile screen size. These are the 'Manage Staking', 'Convert' and 'Manage Delegation' modals on the `/account` route

**Review by dirkpage — COMMENTED** [review]
Okay great I've ran through an entire governance cycle with these changes and there are just a few more changes. 

1. Claim proposal refund modal: the "Move to your wallet" and "Eth Address" text looks weird on mobile, on staging it's side by side which looks fine for desktop but on short width screens maybe it should be top and bottom instead.

image

2. the "read more about it" is different than what we have on staging right now where there is a "MORE" button. I think it looks better with the "MORE" button but if that doesn't fit on mobile we can keep this change, however the link icon needs to veritcally line up with the text (See screenshot below).

image

3. Other than the changes above, please ensure to remove any logs that were added for debugging, and any errors that are logged to the console as a result of changes from this PR are solved.

**Comment by flarcos** [comment]
@paged1  kindly confirm the updated

**Comment by dirkpage** [comment]
Thank you. I think this is ready to merge. I'm going to make sure the ecomponents repo PR is merged and updated first so that this can point to the new dependency version.

https://github.com/eco-association/ecomponents/pull/2

**Comment by flarcos** [comment]
cool...

**Comment by flarcos** [comment]
any idea when this will be merged @paged1

**Comment by carlosfebres** [comment]
Please update the `@ecoinc/ecomponents` library to `v1.1.0`

**Comment by flarcos** [comment]
updated

**Comment by carlosfebres** [comment]
Thank you! @paged1 let's take a final look after these changes and merge if it's all good 🚀

**Comment by carlosfebres** [comment]
[This commit](https://github.com/eco-association/eco-community-dapp/pull/4/commits/977bafd7f44e3b56d259213f6fe40aa33143043e) should also update the `yarn.lock` file, could you also include that, please?

**Comment by dirkpage** [comment]
Thanks for updating the dependency! I ran it and noticed the header has a weird left/right padding now, here's a screenshot of what I see:
image

Let me know if that was intentional but if not it should be fixed. Other than that I think it's good to merge! @carlosfebres

**Review by dirkpage — APPROVED** [review]

**Review by shahrukhtrao — APPROVED** [review]

**Pull request merged**
